# Site settings
title: Girls Do Hack
email: kelly@zooniverse.org
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adlerplanetarium.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
